<?php

namespace App\Filament\Resources\CreditNotes\Pages;

use Filament\Actions\DeleteAction;
use App\Filament\Resources\CreditNotes\CreditNoteResource;
use App\Models\SaleItem;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;
use JetBrains\PhpStorm\NoReturn;

class CreateCreditNote extends CreateRecord
{
    protected static string $resource = CreditNoteResource::class;
    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }
    protected static bool $canCreateAnother = false;
    public function mutateFormDataBeforeCreate(array $data): array
    {
//        dd($data);
        $data['wherehouse_id'] = auth()->user()->employee->branch_id;

        if ($data['document_type_id'] == 6) {
            $data['operation_type'] = 'ND';
        } elseif ($data['document_type_id'] == 4) {
            $data['operation_type'] = 'NR';
        } else {
            $data['operation_type'] = 'NC';
        }

//        $data['operation_type'] = $data['document_type_id']=="6"?'ND':'NC';
        $data['is_invoiced'] = false;
        $data['sales_payment_status'] = 'Pendiente';
        $data['is_invoiced'] = false;
        return $data;

    }
    protected function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label('Iniciar NC')
                ->color('success')
                ->icon('heroicon-o-check')
                ->action('create')
                ->extraAttributes([
                    'class' => 'alig', // Tailwind para ajustar el margen alinearlo a la derecha

                ]),

            Action::make('cancelSale')
                ->label('Cancelar proceso')
                ->icon('heroicon-o-no-symbol')
                ->color('danger')
                ->requiresConfirmation()
                ->modalHeading('Confirmación!!')
                ->modalSubheading('¿Estás seguro de que deseas cancelar esta venta? Esta acción no se puede deshacer.')
                ->modalButton('Sí, cancelar venta')
                ->action(function (DeleteAction $delete) {
                    if (!$this->record) {
                        $this->redirect(static::getResource()::getUrl('index'));
                        return;
                    }
                    if ($this->record->operation_type == "Order") {
                        Notification::make()
                            ->title('Error al anular venta')
                            ->body('No se puede cancelar una orden')
                            ->danger()
                            ->send();
                        return;
                    }

// Elimina la venta y los elementos relacionados
                    SaleItem::where('sale_id', $this->record->id)->delete();
                    $this->record->delete();

// Redirige al índice
                    $this->redirect(static::getResource()::getUrl('index'));

                }),
        ];
    }
}
